# Generated by Django 6.0.1 on 2026-07-25 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=250, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=250, verbose_name="نام خانوادگی"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="شماره تلفن"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("datetime_created", models.DateField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="یوزر",
                    ),
                ),
            ],
        ),
    ]
