# Generated by Django 6.0.1 on 2026-07-26 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactform",
            options={
                "ordering": ["-datetime_created"],
                "verbose_name": "فرم تماس",
                "verbose_name_plural": "فرم تماس ها",
            },
        ),
        migrations.AddField(
            model_name="contactform",
            name="message",
            field=models.TextField(default="", verbose_name="پیام"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contactform",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="یوزر",
            ),
        ),
    ]
