# Generated by Django 6.0.1 on 2026-07-17 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="blog_author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="نویسنده",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="photo",
            field=models.ImageField(upload_to="blog_photos", verbose_name="عکس مقاله"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=200, unique=True, verbose_name="اسلاگ"
            ),
        ),
    ]
