# Generated by Django 6.0.1 on 2026-07-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_category_blog_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["-datetime_created"],
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقالات",
            },
        ),
    ]
