# Generated by Django 6.0.1 on 2026-07-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="تأیید شده"),
        ),
    ]
