# Generated by Django 6.0.1 on 2026-08-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "verbose_name": "پروفایل",
                "verbose_name_plural": "پروفایل\u200cها",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                verbose_name="تصویر پروفایل",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, verbose_name="درباره من"),
        ),
    ]
