# Generated by Django 6.0.1 on 2026-07-28 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoneCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نام دسته\u200cبندی"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=120, unique=True),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی سنگ",
                "verbose_name_plural": "دسته\u200cبندی\u200cهای سنگ",
            },
        ),
        migrations.CreateModel(
            name="ToolCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نام دسته\u200cبندی"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=120, unique=True),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی ابزار",
                "verbose_name_plural": "دسته\u200cبندی\u200cهای ابزار",
            },
        ),
        migrations.CreateModel(
            name="Stone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=220,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="inventory/",
                        verbose_name="تصویر",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_modified", models.DateTimeField(auto_now=True)),
                (
                    "origin",
                    models.CharField(blank=True, max_length=150, verbose_name="منشأ"),
                ),
                (
                    "dimensions",
                    models.CharField(blank=True, max_length=100, verbose_name="ابعاد"),
                ),
                (
                    "thickness",
                    models.CharField(blank=True, max_length=50, verbose_name="ضخامت"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stones",
                        to="inventory.stonecategory",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "سنگ",
                "verbose_name_plural": "سنگ\u200cها",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=220,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="inventory/",
                        verbose_name="تصویر",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_modified", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.CharField(blank=True, max_length=150, verbose_name="برند"),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("good", "سالم"),
                            ("repair", "نیاز به تعمیر"),
                            ("broken", "خراب"),
                        ],
                        default="good",
                        max_length=10,
                        verbose_name="وضعیت سلامت",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tools",
                        to="inventory.toolcategory",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "ابزار",
                "verbose_name_plural": "ابزارها",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
    ]
