# Generated by Django 6.0.1 on 2026-08-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stone',
            options={'ordering': ['-datetime_created'], 'verbose_name': 'سنگ', 'verbose_name_plural': 'سنگ\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['-datetime_created'], 'verbose_name': 'ابزار', 'verbose_name_plural': 'ابزارها'},
        ),
    ]
